### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by marcostenta** [w-jaworski/xlib#1]
Hi, I have a compilation problem

 > [14/31] RUN  make:
#18 0.178 ocamlc -linkall -a -o xlib.cma -I +zip -I +bz2 xstring.ml file.ml int.ml xlist.ml xset.ml xmap.ml bitArray.ml
xstd.ml xunicode.ml extArray.ml xlatex.ml lexer.ml xjson.mli xjson.ml
#18 0.188 File "file.ml", line 48, characters 43-44:
#18 0.188 48 |   let n = Gzip.input ic s 0 (String.length s) in
#18 0.188                                                 ^
#18 0.188 Error: This expression has type bytes but an expression was expected of type
#18 0.188          string
#18 0.190 make: *** [makefile:18: xlib.cma] Error 2
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c make]: exit code: 2

from this post I read:
Since OCaml 4.10.0, the distinction between immutable string and mutable bytes is a configure-time default that cannot be changed on a program-by-program basis.

https://stackoverflow.com/questions/65609284/string-blit-fails-with-error-this-expression-has-type-string-but-an-expression

Is there anything you could do to adapt the code to this new requirement? very likely same problem applies to https://github.com/w-jaworski/AtomMap.git

Thanks a lot for your help.

Kind regards

Marco

**Comment by rmtfleming** [comment]
Same compilation issue still exists 

xlib$ sudo make install
ocamlc -linkall -a -o xlib.cma -I +zip -I +bz2 xstring.ml file.ml int.ml xlist.ml xset.ml xmap.ml bitArray.ml xstd.ml xunicode.ml extArray.ml xlatex.ml lexer.ml xjson.mli xjson.ml xjsonSchema.mli xjsonSchema.ml trie.ml
File "file.ml", line 48, characters 43-44:
48 |   let n = Gzip.input ic s 0 (String.length s) in
                                                ^
Error: This expression has type bytes but an expression was expected of type
         string
make: *** [makefile:18: xlib.cma] Error 2

Some info on my system...
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

$ ocaml -version
The OCaml toplevel, version 4.08.1

**Comment by rmtfleming** [comment]
This approach did not fix the issue...
 https://stackoverflow.com/questions/65609284/string-blit-fails-with-error-this-expression-has-type-string-but-an-expression
In xlib, change makefile line 18 to:
	ocamlc -linkall -unsafe-string -a -o xlib.cma $(OCAMLFLAGS) $^
	
Neither did...
 Install batteries: http://batteries.forge.ocamlcore.org/doc.preview:batteries-beta1/html/api/Big_int.html (requires opam to be installed, initialised, etc)

**Comment by w-jaworski** [comment]
The cause of the problem was that ocaml ceased to be backward compatible. I have pushed new version of the library which should work with ocaml compiler in version 4.11.1. There is also a new dependency: libzarith-ocaml-dev
